main: org.golde.snowball.plugin.MainPlugin
name: SnowballAPI
version: 1.0
description: "A API for the Snowball Client"
depend: [ProtocolLib]
author: Eric Golde
website: https://eric.golde.org/
load: STARTUP
loadbefore: [HolographicDisplays]